FROM python:3.11-slim
WORKDIR /mlflow

# Install MLflow
RUN pip install --no-cache-dir mlflow

# Expose UI port
EXPOSE 5000

# Start MLflow server
CMD ["mlflow", "server", "--backend-store-uri", "/mlflow/mlruns", "--default-artifact-root", "/mlflow/mlruns", "--host", "0.0.0.0", "--port", "5000"]
